fixed code snippet and text errors
learn-co-curriculum/intro-app-state-redux pull request #1
Opened 2016-12-15 11:23 UTC by Lukeghenco

Updated the code snippet to be cleaner and more readable (added constructor, initial state and a checked attribute to the input tag), I also cleaned up some of the written text and styling.

@aturkewi @PeterBell

2016-12-18 20:53 UTC, aturkewi requested changes
Made a couple of comments. Let me know what you think!

2016-12-18 20:53 UTC, aturkewi commented on README.md
> +import React, { Component } from 'react'
If you're going to only import `Component` from React, then you need to update the syntax on line 32 to be `class myCheckBox extends Component {`

2016-12-18 20:53 UTC, aturkewi commented on README.md
>  ```
Can you add `js` right after the three backticks (no space) so we get some JS formatting?

2016-12-18 20:53 UTC, aturkewi commented on README.md
> +State in Redux is similar to state in React but at a larger scale. While state in React is focused on an individual component and its children, **Redux holds the state for our whole application**. Re
Given that this curriculum is supposed to be for online and in person, how do you feel about changing the last sentence to something like: "We need to keep track of the students that have graduated." or something more generic like that?

2016-12-20 20:26 UTC, Lukeghenco commented on README.md
> +State in Redux is similar to state in React but at a larger scale. While state in React is focused on an individual component and its children, **Redux holds the state for our whole application**. Re
fixed

2016-12-20 20:27 UTC, Lukeghenco reviewed
finished

2016-12-20 20:48 UTC, merged